<?xml version="1.0" encoding="utf-8"?><Database Name="EFMM" Class="EFMMDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=zugsql01;Initial Catalog=EFMM;Persist Security Info=True;User ID=writer" SettingsObjectName="bloomberg_downloader.Properties.Settings" SettingsPropertyName="EFMMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bloomberg_download" Member="bloomberg_downloads">
    <Type Name="bloomberg_download">
      <Column Name="date_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="ticker" Type="System.String" DbType="VarChar(400) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="vwap_volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="vwap_lit_volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="px_last_in_euro" Type="System.Decimal" DbType="Decimal(32,8) NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="record_created" AutoSync="Never" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
    </Type>
  </Table>
  <Function Name="dbo.insert_bloomberg_download" Method="insertBloombergDownload">
    <Parameter Name="aDateId" Type="System.Int32" DbType="Int" />
    <Parameter Name="aPxLast" Type="System.Decimal" DbType="Decimal(32,8)" />
    <Parameter Name="aVwapVolume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="aVwapLitVolume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="aTicker" Type="System.String" DbType="VarChar(400)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_bloomberg_tickers" Method="getBloombergTickers">
    <Parameter Name="aExchangesIn" Type="System.String" DbType="VarChar(4000)" />
    <ElementType Name="get_bloomberg_tickersResult">
      <Column Name="value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>