#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bloomberg_downloader
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Reflection;
    using System.ComponentModel;
    using System;
    
    
    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EFMM")]
    public partial class EFMMDataClassesDataContext : System.Data.Linq.DataContext
    {
        
        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
        
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbloomberg_download(bloomberg_download instance);
    partial void Updatebloomberg_download(bloomberg_download instance);
    partial void Deletebloomberg_download(bloomberg_download instance);
    #endregion
        
        public EFMMDataClassesDataContext() : 
                base(global::bloomberg_downloader.Properties.Settings.Default.EFMMConnectionString, mappingSource)
        {
            OnCreated();
        }
        
        public EFMMDataClassesDataContext(string connection) : 
                base(connection, mappingSource)
        {
            OnCreated();
        }
        
        public EFMMDataClassesDataContext(System.Data.IDbConnection connection) : 
                base(connection, mappingSource)
        {
            OnCreated();
        }
        
        public EFMMDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
                base(connection, mappingSource)
        {
            OnCreated();
        }
        
        public EFMMDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
                base(connection, mappingSource)
        {
            OnCreated();
        }
        
        public System.Data.Linq.Table<bloomberg_download> bloomberg_downloads
        {
            get
            {
                return this.GetTable<bloomberg_download>();
            }
        }
        
        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_bloomberg_download")]
        public int insertBloombergDownload([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> aDateId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(32,8)")] System.Nullable<decimal> aPxLast, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> aVwapVolume, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> aVwapLitVolume, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(400)")] string aTicker)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aDateId, aPxLast, aVwapVolume, aVwapLitVolume, aTicker);
            return ((int)(result.ReturnValue));
        }
        
        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_bloomberg_tickers")]
        public ISingleResult<get_bloomberg_tickersResult> getBloombergTickers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4000)")] string aExchangesIn)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aExchangesIn);
            return ((ISingleResult<get_bloomberg_tickersResult>)(result.ReturnValue));
        }
    }
    
    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bloomberg_download")]
    public partial class bloomberg_download : INotifyPropertyChanging, INotifyPropertyChanged
    {
        
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
        
        private int _date_id;
        
        private string _ticker;
        
        private long _vwap_volume;
        
        private long _vwap_lit_volume;
        
        private decimal _px_last_in_euro;
        
        private System.DateTimeOffset _record_created;
        
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondate_idChanging(int value);
    partial void Ondate_idChanged();
    partial void OntickerChanging(string value);
    partial void OntickerChanged();
    partial void Onvwap_volumeChanging(long value);
    partial void Onvwap_volumeChanged();
    partial void Onvwap_lit_volumeChanging(long value);
    partial void Onvwap_lit_volumeChanged();
    partial void Onpx_last_in_euroChanging(decimal value);
    partial void Onpx_last_in_euroChanged();
    partial void Onrecord_createdChanging(System.DateTimeOffset value);
    partial void Onrecord_createdChanged();
    #endregion
        
        public bloomberg_download()
        {
            OnCreated();
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
        public int date_id
        {
            get
            {
                return this._date_id;
            }
            set
            {
                if ((this._date_id != value))
                {
                    this.Ondate_idChanging(value);
                    this.SendPropertyChanging();
                    this._date_id = value;
                    this.SendPropertyChanged("date_id");
                    this.Ondate_idChanged();
                }
            }
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticker", DbType="VarChar(400) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
        public string ticker
        {
            get
            {
                return this._ticker;
            }
            set
            {
                if ((this._ticker != value))
                {
                    this.OntickerChanging(value);
                    this.SendPropertyChanging();
                    this._ticker = value;
                    this.SendPropertyChanged("ticker");
                    this.OntickerChanged();
                }
            }
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vwap_volume", DbType="BigInt NOT NULL")]
        public long vwap_volume
        {
            get
            {
                return this._vwap_volume;
            }
            set
            {
                if ((this._vwap_volume != value))
                {
                    this.Onvwap_volumeChanging(value);
                    this.SendPropertyChanging();
                    this._vwap_volume = value;
                    this.SendPropertyChanged("vwap_volume");
                    this.Onvwap_volumeChanged();
                }
            }
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vwap_lit_volume", DbType="BigInt NOT NULL")]
        public long vwap_lit_volume
        {
            get
            {
                return this._vwap_lit_volume;
            }
            set
            {
                if ((this._vwap_lit_volume != value))
                {
                    this.Onvwap_lit_volumeChanging(value);
                    this.SendPropertyChanging();
                    this._vwap_lit_volume = value;
                    this.SendPropertyChanged("vwap_lit_volume");
                    this.Onvwap_lit_volumeChanged();
                }
            }
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_px_last_in_euro", DbType="Decimal(32,8) NOT NULL")]
        public decimal px_last_in_euro
        {
            get
            {
                return this._px_last_in_euro;
            }
            set
            {
                if ((this._px_last_in_euro != value))
                {
                    this.Onpx_last_in_euroChanging(value);
                    this.SendPropertyChanging();
                    this._px_last_in_euro = value;
                    this.SendPropertyChanged("px_last_in_euro");
                    this.Onpx_last_in_euroChanged();
                }
            }
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_created", DbType="DateTimeOffset NOT NULL", IsDbGenerated=true, IsVersion=true)]
        public System.DateTimeOffset record_created
        {
            get
            {
                return this._record_created;
            }
            set
            {
                if ((this._record_created != value))
                {
                    this.Onrecord_createdChanging(value);
                    this.SendPropertyChanging();
                    this._record_created = value;
                    this.SendPropertyChanged("record_created");
                    this.Onrecord_createdChanged();
                }
            }
        }
        
        public event PropertyChangingEventHandler PropertyChanging;
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }
        
        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    public partial class get_bloomberg_tickersResult
    {
        
        private string _value;
        
        public get_bloomberg_tickersResult()
        {
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(50)")]
        public string value
        {
            get
            {
                return this._value;
            }
            set
            {
                if ((this._value != value))
                {
                    this._value = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
